In [2]:
import numpy as np

In [2]:
a = [1,2,3,4]
type(a)

list

In [3]:
b =  np.array(a)
b

array([1, 2, 3, 4])

In [4]:
type(b)

numpy.ndarray

In [9]:
x = [1,3,5,6,] 
y = np.array(x)
y
type(y)


numpy.ndarray

In [89]:
# array.shape         # return how many row and how many column (row,column)

# array.size         # return size of array row*column

# array.ndim        # ndim means number of dimention  

# l1.dtype       # return which type of data are store   l1= array

# le.astype(int)  # convert on array to a different type

# len(l1)            # return length 

In [11]:
# .shape

print("toal shape :",b.shape)   # 4 column and 1 row

toal shape : (4,)


In [12]:
# .Size   ==> row * columm

print("Total size :",b.size)

Total size : 4


In [13]:
# .ndim    ==> refer to  dimension of array


print("Total dimension :",b.ndim)

Total dimension : 1


In [20]:
# 2-D dimension

a = [ [1,2,3],[4,5,6] ,[6,7,8] ]

a

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [21]:
b   = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
b.shape

(3, 3)

In [25]:
print("Total row and column :",b.shape)

print("Total element :",b.size)

print("Toak Dimension :",b.ndim)

Total row and column : (3, 3)
Total element : 9
Toak Dimension : 2


# How can we create a suse defined Array?

In [29]:
a  = []
size = int(input("enter the size:"))
for i in range(size):
    val = int(input("enter the value :"))
    a.append(val)

b=  np.array(a)
b

enter the siz: 5
enter the value : 1
enter the value : 2
enter the value : 3
enter the value : 4
enter the value : 5


array([1, 2, 3, 4, 5])

# Numpy Functions

In [34]:
# Images  ===> pixels (0-255)px  ===> 0px(black),255(white) ====> Normalize ===>(0-1) px


# a :  Black & White  ===> height, width
# b:   Colorfull Image  ==> height ,width,color_channel(red,green,blue)    # RGBm

# matrix  ==> Number(row) = number(column)  --> Symmatric matrix

               # Number(row) != number(column)  --> ASymmatric matrix 


# random Number generation ==> random() module

# Data Science ==>  Simple line equation :  y = mx + b  where x,y  = Cordinates and b is intercept(minimum value we can not effect the mx but case if m and x if one is zero to use the b



# matrix   ==> row,column

# matrix  ==> digonal positional element  = [(1,1),(2,2),(3,3),.....,(n,n)]


# 1: zeros() ==> it will create and array in which all values are 0

seperated by .,

In [35]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [36]:
a = np.zeros((2,3))     # 2 row and 3 column

a

array([[0., 0., 0.],
       [0., 0., 0.]])

# 2: ones() ==> It will create an array in which all the values are 1.

In [37]:
a = np.ones(3)
a

array([1., 1., 1.])

In [38]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 3: eye()  ==>  it will create an array in which digonal positional elements are 1 and rest all are 0

it will not create 1-D

In [14]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a = np.eye(4,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

# 4: diag()  ==> It will create an array in which we can customize our digonal positional elements 

In [45]:
a = np.diag([10,20,30,40])
a

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

# 5: Random Module  
 a: otp generation
 
 b: Dataset  ==>  1 dummy column add
 
 c: randomly weights initialize 


# a: Randint(min_number,max_number,total_numbers)     
total number means mininum number or maximum number ke bech m kitne random number chaiye


In [20]:
a = np.random.randint(1,10,3)
a

array([7, 7, 8])

In [16]:
a = np.random.randint(1,10,4)
a

array([3, 6, 9, 1])

# b: Rand(total_numbers)  ==> It will return numbers from 0 to 1 

In [81]:
a = np.random.rand(4)
a

array([0.76285165, 0.22296392, 0.09423808, 0.4996985 ])

# c: Randn()  ==>   -3 to 3

In [82]:
a = np.random .randn(5)

a

array([-0.37927179, -0.70965625,  0.51473534, -1.45928734, -0.12583132])

# d: Seed() ==> It will fix our data once the data has been generated

In [90]:
np.random.seed(30)                # where 30 is use to fix generated value

a  = np.random.randint(1,10,3)
a

array([6, 6, 5])