# View vs Copy

 view change original data 

 copy change only duplicate data we can not affect original data

In [2]:
import numpy as np

In [4]:
a = np.array([10,20,30,40,50,60,70,80])   # view means modification of original data
a
b= a[2:5]
b
b[:] = 0               # all element are 0
a



array([10, 20,  0,  0,  0, 60, 70, 80])

In [6]:
a = np.array([10,20,30,40,50,60,70,80])   # Copy means modification in duplicate data

b  = a[2:5].copy()
b
b[:] = 0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80])

# Reshapping the data

In [14]:
# we know that 

# n(row) * n(column)  = n(total_element)

# if we have total_element  =12

# 1*12 ,12*1
# 2*6,  6*2
# 3*4 , 4*3



# if we have total_elements = 36

# 1*36 , 36*1
# 2*18 ,18*2
# 3*12 , 12*3
# 4*9 , 9*4
# 6*6

In [15]:
a = np.random.randint(1,50,12)
a

array([ 6, 46, 40,  8, 29, 10, 21, 27,  6, 48, 18, 18])

In [16]:
a.shape

(12,)

In [17]:
a.reshape(2,6)

array([[ 6, 46, 40,  8, 29, 10],
       [21, 27,  6, 48, 18, 18]])

In [18]:
a.reshape(4,3)

array([[ 6, 46, 40],
       [ 8, 29, 10],
       [21, 27,  6],
       [48, 18, 18]])

In [22]:
a.reshape(6,2)

array([[ 6, 46],
       [40,  8],
       [29, 10],
       [21, 27],
       [ 6, 48],
       [18, 18]])

In [23]:
# min_number = 1
# max_number = 100
# total_number = 72

# Reshape all the data?

# 1*72  , 72*1
# 2*36 , 36*2
# 3*24 ,24*3
# 4*18 ,18*4
# 6*12 ,12*6
# 8*9 , 9*8




# Conditional Selection In Numpy

In [14]:
 # .arange()

a = np.arange(1,8,2)
a

array([1, 3, 5, 7])

In [15]:
a  = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [17]:
a<10


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [18]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [20]:
a%2==0


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [21]:
a[a%2==0]      # Even number 

array([ 2,  4,  6,  8, 10, 12, 14])

In [22]:
a[a%2!=0]     #Odd Number

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [29]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a  = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [37]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [38]:
# Sum of two matrix 

a+b

array([[ 6,  8],
       [10, 12]])

In [39]:
# Subtraction of a and b

a - b

array([[-4, -4],
       [-4, -4]])

In [40]:
# Wrong way  Mltiplication of a and b

a*b

array([[ 5, 12],
       [21, 32]])

In [44]:
# Write way Matrix multiplication

a.dot(b)

array([[19, 22],
       [43, 50]])

In [46]:
a  = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.sum(a)      #  Sum Of Total Number Of Elements

45

In [50]:
np.sum(a,axis = 1)        # Sum Of Row Wise 


array([ 6, 15, 24])

In [52]:
np.sum(a, axis=0)          #  Column Wise Sum

array([12, 15, 18])

# Unique()   ==>   It will return unique values or eliminate duplicate values 

It will return 3 array

1:  Unique value's array

2:  Indexing of original value

3:  Return frequency of each unique value

In [53]:
a = np.array([1,2,2,2,3,3,4,4,4,4,4,5,6,6])
a

array([1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 6, 6])

In [54]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [56]:
np.unique(a,return_index = True ,return_counts = True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  6, 11, 12], dtype=int64),
 array([1, 3, 2, 5, 1, 2], dtype=int64))

# Linspace()  ==>  It will create an array in which diffrence of each value will be equal

In [65]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# Stacking in Numpy 

1:  hstack()  ==> It will Combined multiple arrays into horizontally 

2:  vstack()  ==> It will Combined multiple arraysz into vertically 

In [5]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

a

array([1, 2, 3, 4])

In [84]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [85]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])