In [1]:
import numpy as np

In [2]:
# Q.1: Create an array using numpy?

a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [9]:
# Q.2: Create an array of 10 random integers ?

a = np.random.randint(1,10,10)
a

array([4, 8, 7, 4, 4, 7, 9, 2, 4, 3])

In [10]:
# Q.3: Create an array elements from 10-20 ?

a = np.arange(10,20)
a




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
# Q.4: Create an array which contain value 5,10 times?

a = np.array([5]*10)
a



array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [19]:
# Q.5: Create a one dimensional array and convert that into 3*3 matrix ?

a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
a = np.arange(9)
a.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# Q.6: Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?

a = np.random.rand(3,3)
a

array([[0.0258757 , 0.03262146, 0.32275938],
       [0.09157151, 0.74325799, 0.92722953],
       [0.13058269, 0.28628671, 0.54834931]])

In [41]:
# Q.7: Concatenate 2D array horizontally and vertically ?

a = np.array([[1,2],[3,4]])
a
b = np.array([[5,6],[7,8]])
b


h_stack = np.hstack((a,b))
h_stack


v_stack = np.vstack((a,b))
v_stack




array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])